# Generated by Django 5.1.6 on 2025-02-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='default.svg', max_length=64),
        ),
    ]
