# Generated by Django 5.1.6 on 2025-03-04 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_room_users_user_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
